#ifndef DACSPI_FIQ_H
#define	DACSPI_FIQ_H

#define DSIDX_WAVEFORM_ADDR 0
#define DSIDX_PHASE 1
#define DSIDX_SAMPLE_COUNT 2
#define DSIDX_INCREMENT 3
#define DSIDX_INTERP_RATIO 4
#define DSIDX_PERIOD 5
#define DSIDX_INTERP_LAST_SAMPLE 6
#define DSIDX_DEBUG 7

#define DS_INTERP_ALPHA_SHIFT 6

#endif	/* DACSPI_FIQ_H */

